version: '3.8'
services:
  backend:
    build: ./back
    environment:
      - BACK_JSON=${BACK_JSON}   
    ports:
      - "8081:8081"


  frontend:
    build: ./front
    environment:
      - FRONT_JSON=${FRONT_JSON} 
    ports:
      - "80:8080"  
    depends_on:
      - backend
