services:
  backend:
    build: ./back
    volumes:
      - ~/secrets/back.json:/run/secrets/back  # <-- Mounte die Datei
    ports:
      - "8081:8081"

  frontend:
    build: ./front
    volumes:
      - ~/secrets/front.json:/run/secrets/front  # <-- Mounte die Datei
    ports:
      - "80:80"
    depends_on:
      - backend