services:
  backend:
    build: ./back
    container_name: chat-ai-backend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8081" 
    volumes:
      - ~/secrets/back.json:/run/secrets/back

  frontend:
    build: ./front
    container_name: chat-ai-frontend
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"  
    volumes:
      - ~/secrets/front.json:/run/secrets/front
    depends_on:
      - backend