name: Deploy to OpenStack

on:
  push:
    branches: 
      - main
      - dev
      - stt-llm-tts+vision

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Run with Docker Compose
        env:
          BACK_JSON: ${{ secrets.BACK_JSON }}
          FRONT_JSON: ${{ secrets.FRONT_JSON }}
        run: |
          docker compose down || true
          docker compose up -d --build
          docker image prune -f